token = "bot_token"
owners = [ 141231597155385344, ]
default_prefix = "i."  # The prefix for the bot's commands
guild_id = 1  # The ID of the main/support guild

# Data that's copied directly over to a command without processing
[command_data]
    guild_invite = ""
    github = ""
    patreon = ""

# This data is passed directly over to asyncpg
[database]
    user = "itembot"
    password = "DatabasePassword"
    database = "itembot"
    host = "127.0.0.1"
    port = 5432
    enabled = true

# This data is passed directly over to aioredis
[redis]
    host = "127.0.0.1"
    port = 6379
    db = 0
    enabled = false

# What the bot is playing
[presence]
    activity_type = "watching"  # Should be one of 'playing', 'listening', 'watching'
    text = "your stuff (i.help)"
    status = "online"  # Should be one of 'online', 'invisible', 'idle', 'dnd'

# Used to generate the invite link - client ID only necessary for webserver
[oauth]
    client_id = ""
    client_secret = ""
